// Code generated by protoc-gen-go. DO NOT EDIT.
// source: biz.proto

package biz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKey              int32    `protobuf:"varint,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4f2476de321c17, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Request) GetAuthKey() int32 {
	if m != nil {
		return m.AuthKey
	}
	return 0
}

func (m *Request) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type Result struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	MessageId            int32    `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4f2476de321c17, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Result) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type RequestSqlInject struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKey              int32    `protobuf:"varint,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSqlInject) Reset()         { *m = RequestSqlInject{} }
func (m *RequestSqlInject) String() string { return proto.CompactTextString(m) }
func (*RequestSqlInject) ProtoMessage()    {}
func (*RequestSqlInject) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4f2476de321c17, []int{2}
}

func (m *RequestSqlInject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSqlInject.Unmarshal(m, b)
}
func (m *RequestSqlInject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSqlInject.Marshal(b, m, deterministic)
}
func (m *RequestSqlInject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSqlInject.Merge(m, src)
}
func (m *RequestSqlInject) XXX_Size() int {
	return xxx_messageInfo_RequestSqlInject.Size(m)
}
func (m *RequestSqlInject) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSqlInject.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSqlInject proto.InternalMessageInfo

func (m *RequestSqlInject) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RequestSqlInject) GetAuthKey() int32 {
	if m != nil {
		return m.AuthKey
	}
	return 0
}

func (m *RequestSqlInject) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Family               string   `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  string   `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd4f2476de321c17, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "request")
	proto.RegisterType((*Result)(nil), "result")
	proto.RegisterType((*RequestSqlInject)(nil), "request_sql_inject")
	proto.RegisterType((*User)(nil), "user")
}

func init() {
	proto.RegisterFile("biz.proto", fileDescriptor_dd4f2476de321c17)
}

var fileDescriptor_dd4f2476de321c17 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcb, 0x4b, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0x24, 0x4d, 0xd2, 0xdc, 0x0f, 0x7c, 0x5c, 0x41, 0x53, 0x1f, 0x50, 0xba, 0xea,
	0x2a, 0x42, 0x5d, 0xba, 0x52, 0xdc, 0x14, 0x77, 0x5d, 0x8a, 0x30, 0x4c, 0x3a, 0xd7, 0x74, 0x34,
	0x69, 0xda, 0xcc, 0x84, 0x3e, 0xd6, 0xfe, 0xe1, 0x32, 0x93, 0x50, 0x4b, 0xbb, 0x75, 0x77, 0xcf,
	0xb9, 0x73, 0x7f, 0x1c, 0x0e, 0x03, 0x51, 0x2a, 0xb7, 0xc9, 0xa2, 0x2a, 0x75, 0x39, 0x78, 0x87,
	0xb0, 0xa2, 0x65, 0x4d, 0x4a, 0xe3, 0x15, 0x84, 0xb5, 0xa2, 0x8a, 0x49, 0x11, 0x3b, 0x7d, 0x67,
	0xe8, 0x4f, 0x02, 0x23, 0xc7, 0x02, 0x7b, 0xd0, 0xe5, 0xb5, 0x9e, 0xb1, 0x2f, 0xda, 0xc4, 0xae,
	0xdd, 0x84, 0x46, 0xbf, 0xd2, 0x06, 0xef, 0x00, 0x0a, 0x52, 0x8a, 0x67, 0x64, 0xce, 0x3c, 0xbb,
	0x8c, 0x5a, 0x67, 0x2c, 0x06, 0x2f, 0x10, 0x54, 0xa4, 0xea, 0x5c, 0xe3, 0x0d, 0xf8, 0x86, 0xa6,
	0x62, 0xa7, 0xef, 0x0d, 0xff, 0x8f, 0xfc, 0xc4, 0xa8, 0x49, 0xe3, 0x1d, 0x50, 0xdc, 0x43, 0x4a,
	0x06, 0xd8, 0x66, 0x64, 0x6a, 0x99, 0x33, 0x39, 0xff, 0xa4, 0xe9, 0x51, 0xdc, 0xe8, 0x0f, 0xe2,
	0x7e, 0x3b, 0xd0, 0x31, 0x10, 0x44, 0xe8, 0xcc, 0x79, 0x41, 0x2d, 0xd8, 0xce, 0x78, 0x09, 0xc1,
	0x07, 0x2f, 0x64, 0xde, 0x40, 0xa3, 0x49, 0xab, 0xf0, 0x04, 0xdc, 0x1d, 0xcb, 0x95, 0x02, 0xcf,
	0xc0, 0xe3, 0x19, 0xc5, 0x1d, 0x6b, 0x98, 0xd1, 0x38, 0x8a, 0xd6, 0xb1, 0x6f, 0xcf, 0xcc, 0x88,
	0xb7, 0x10, 0x4d, 0x2b, 0xe2, 0x9a, 0xc4, 0x93, 0x8e, 0x03, 0xeb, 0xff, 0x1a, 0x23, 0x01, 0xde,
	0x8a, 0x52, 0xec, 0x43, 0x94, 0x91, 0x66, 0x4d, 0x45, 0xdd, 0xa4, 0xad, 0xe0, 0x3a, 0x4c, 0x9a,
	0x4a, 0x07, 0xff, 0xf0, 0x11, 0x7a, 0xbb, 0x17, 0x6c, 0x25, 0xf5, 0x6c, 0xbf, 0x9f, 0x8b, 0xe4,
	0xb8, 0xb4, 0xbd, 0xe3, 0xe7, 0xf3, 0xb7, 0x53, 0x5a, 0xf3, 0x62, 0x91, 0x53, 0x32, 0x2d, 0x8b,
	0xfb, 0x54, 0x6e, 0xd3, 0xc0, 0xfe, 0x89, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x48,
	0x1e, 0x55, 0x20, 0x02, 0x00, 0x00,
}
