// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestPq struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MessageId            int32    `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPq) Reset()         { *m = RequestPq{} }
func (m *RequestPq) String() string { return proto.CompactTextString(m) }
func (*RequestPq) ProtoMessage()    {}
func (*RequestPq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *RequestPq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPq.Unmarshal(m, b)
}
func (m *RequestPq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPq.Marshal(b, m, deterministic)
}
func (m *RequestPq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPq.Merge(m, src)
}
func (m *RequestPq) XXX_Size() int {
	return xxx_messageInfo_RequestPq.Size(m)
}
func (m *RequestPq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPq proto.InternalMessageInfo

func (m *RequestPq) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *RequestPq) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type ResultPq struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          string   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	P                    int32    `protobuf:"varint,4,opt,name=p,proto3" json:"p,omitempty"`
	G                    int32    `protobuf:"varint,5,opt,name=g,proto3" json:"g,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultPq) Reset()         { *m = ResultPq{} }
func (m *ResultPq) String() string { return proto.CompactTextString(m) }
func (*ResultPq) ProtoMessage()    {}
func (*ResultPq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *ResultPq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultPq.Unmarshal(m, b)
}
func (m *ResultPq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultPq.Marshal(b, m, deterministic)
}
func (m *ResultPq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultPq.Merge(m, src)
}
func (m *ResultPq) XXX_Size() int {
	return xxx_messageInfo_ResultPq.Size(m)
}
func (m *ResultPq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultPq.DiscardUnknown(m)
}

var xxx_messageInfo_ResultPq proto.InternalMessageInfo

func (m *ResultPq) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *ResultPq) GetServerNonce() string {
	if m != nil {
		return m.ServerNonce
	}
	return ""
}

func (m *ResultPq) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *ResultPq) GetP() int32 {
	if m != nil {
		return m.P
	}
	return 0
}

func (m *ResultPq) GetG() int32 {
	if m != nil {
		return m.G
	}
	return 0
}

type Request_DH struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          string   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	A                    int32    `protobuf:"varint,4,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DH) Reset()         { *m = Request_DH{} }
func (m *Request_DH) String() string { return proto.CompactTextString(m) }
func (*Request_DH) ProtoMessage()    {}
func (*Request_DH) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Request_DH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DH.Unmarshal(m, b)
}
func (m *Request_DH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DH.Marshal(b, m, deterministic)
}
func (m *Request_DH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DH.Merge(m, src)
}
func (m *Request_DH) XXX_Size() int {
	return xxx_messageInfo_Request_DH.Size(m)
}
func (m *Request_DH) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DH.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DH proto.InternalMessageInfo

func (m *Request_DH) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Request_DH) GetServerNonce() string {
	if m != nil {
		return m.ServerNonce
	}
	return ""
}

func (m *Request_DH) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Request_DH) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

type Result_DH struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ServerNonce          string   `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	MessageId            int32    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	B                    int32    `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result_DH) Reset()         { *m = Result_DH{} }
func (m *Result_DH) String() string { return proto.CompactTextString(m) }
func (*Result_DH) ProtoMessage()    {}
func (*Result_DH) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Result_DH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result_DH.Unmarshal(m, b)
}
func (m *Result_DH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result_DH.Marshal(b, m, deterministic)
}
func (m *Result_DH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result_DH.Merge(m, src)
}
func (m *Result_DH) XXX_Size() int {
	return xxx_messageInfo_Result_DH.Size(m)
}
func (m *Result_DH) XXX_DiscardUnknown() {
	xxx_messageInfo_Result_DH.DiscardUnknown(m)
}

var xxx_messageInfo_Result_DH proto.InternalMessageInfo

func (m *Result_DH) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Result_DH) GetServerNonce() string {
	if m != nil {
		return m.ServerNonce
	}
	return ""
}

func (m *Result_DH) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Result_DH) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestPq)(nil), "web.request_pq")
	proto.RegisterType((*ResultPq)(nil), "web.result_pq")
	proto.RegisterType((*Request_DH)(nil), "web.request_DH")
	proto.RegisterType((*Result_DH)(nil), "web.result_DH")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x4f, 0x4d, 0x52, 0x72, 0xe4, 0xe2, 0x2a,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x89, 0x2f, 0x28, 0x14, 0x12, 0xe1, 0x62, 0xcd, 0xcb, 0xcf,
	0x4b, 0x4e, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x64, 0xb9, 0xb8, 0x72,
	0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0xe3, 0x33, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83,
	0x38, 0xa1, 0x22, 0x9e, 0x29, 0x4a, 0xf5, 0x5c, 0x9c, 0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x78, 0x4c,
	0x50, 0xe4, 0xe2, 0x29, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x8a, 0x87, 0x48, 0x32, 0x81, 0x25, 0xb9,
	0x21, 0x62, 0x7e, 0x58, 0x2c, 0x61, 0x46, 0xb3, 0x44, 0x88, 0x87, 0x8b, 0xb1, 0x40, 0x82, 0x05,
	0x2c, 0xca, 0x58, 0x00, 0xe2, 0xa5, 0x4b, 0xb0, 0x42, 0x78, 0xe9, 0x4a, 0x45, 0x08, 0x3f, 0xb8,
	0x78, 0xd0, 0xd2, 0x05, 0x89, 0x30, 0x17, 0x24, 0x2a, 0x15, 0xc2, 0x3d, 0x4d, 0x5b, 0x2b, 0x93,
	0x60, 0x56, 0x26, 0x19, 0xa5, 0x71, 0x81, 0x62, 0x4c, 0x48, 0x9b, 0x8b, 0xad, 0x28, 0xb5, 0x10,
	0x14, 0xd6, 0xfc, 0x7a, 0xe5, 0xa9, 0x49, 0x7a, 0x88, 0xe8, 0x93, 0xe2, 0x83, 0x0a, 0x40, 0x23,
	0x43, 0x89, 0x41, 0xc8, 0x88, 0x8b, 0x17, 0xa4, 0xd8, 0xc5, 0x23, 0xbe, 0x20, 0xb1, 0x28, 0x31,
	0xb7, 0x18, 0x4d, 0x8f, 0x8b, 0x07, 0xaa, 0x1e, 0x17, 0x0f, 0x25, 0x06, 0x27, 0xa1, 0x28, 0x81,
	0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x50, 0x8a, 0x49, 0x62,
	0x03, 0x27, 0x19, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x15, 0xd1, 0xfc, 0x40, 0x02,
	0x00, 0x00,
}
